apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-unification-main
  labels:
    app: document-unification
    deployment: main
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: document-unification
      deployment: main
  template:
    metadata:
      labels:
        app: document-unification
        deployment: main
    spec:
      containers:
      - name: document-unification
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
